export const plans = {
    properties: [
      {
        flow: 1,
        flowName: 'Terminales Libres ',
        procSales: 'TER',
        typePayment:'FIN/MIX',
        typePlan: 'PRE',
        typeSales: 'ACT',
        isValidate: true,
      },
      {
        flow: 2,
        flowName: 'KIT Prepago',
        procSales: 'KIT',
        typePlan: 'PRE',
        typeSales: 'ACT',
        isValidate: false,
      },
      {
        flow: 3,
        flowName: 'Tecnología',
        procSales: 'TEC',
        typePayment:"FIN/MIX",
        typePlan: '',
        typeSales: '',
        isValidate: true,
      },
      {
        flow: 4,
        flowName: 'SIM + Paquete',
        procSales: '',
        typePlan: 'PRE',
        typeSales: 'ACT',
        isValidate: false,
      },
      {
        flow: 5,
        flowName: 'Portabilidad Prepago',
        procSales: '',
        typePlan: 'PRE',
        typeSales: 'POR',
        isValidate: false,
      },
      {
        flow: 6,
        flowName: 'Línea Nueva Postpago',
        procSales: '',
        typePlan: 'POS',
        typeSales: 'ACT',
        isValidate: true,
      },
      {
        flow: 7,
        flowName: 'Portabilidad Postpago',
        procSales: '',
        typePlan: 'POS',
        typeSales: 'POR',
        isValidate: true,
      },
      {
        flow: 8,
        flowName: 'Reposición',
        procSales: '',
        typePlan: 'POS',
        typeSales: 'REPO',
        isValidate: true,
      },
      {
        flow: 9,
        flowName: 'Hogares',
        procSales: 'HOG',
        typePlan: '',
        typeSales: '',
        isValidate: true,
      },
    ],
  };
  