//Enumera las tareas que se realizan en el microservicio
export enum Etask {
    CREATE = 'CREANDO_MOCKUP',
    FINDALL = 'CONSULTANDO_MOCKUPS',
    FINDONE = 'CONSULTANDO_MOCKUP',
    UPDATE = 'ACTUALIZANDO_MOCKUP',
    REMOVE = 'ELIMINANDO_MOCKUP',
    LOAD_MESSAGE = 'CARGANDO_MENSAJES',
    CREATE_SERVICE_ERROR = 'CREATE_SERVICE_ERROR',
    
};